function options = options(varargin)
%BMLA.OPTIONS Create public options for the BMLA solver.
%
%   OPTIONS = BMLA.OPTIONS() returns the default public options.
%
%   OPTIONS = BMLA.OPTIONS(NAME, VALUE, ...) overrides selected options.
%
%   Public options:
%
%       FunctionTolerance  Positive scalar. Default: 1e-8.
%       StepTolerance      Positive scalar. Default: 1e-10.
%       MaxIterations      Positive integer. Default: 500.
%       Display            "off" or "final". Default: "off".
%       ReturnHistory      Logical scalar. Default: false.
%
%   Example:
%
%       opts = bmla.options( ...
%           "FunctionTolerance", 1e-10, ...
%           "MaxIterations", 1000, ...
%           "Display", "final");

    options = struct( ...
        'FunctionTolerance', 1e-8, ...
        'StepTolerance', 1e-10, ...
        'MaxIterations', 500, ...
        'Display', "off", ...
        'ReturnHistory', false);

    if mod(nargin, 2) ~= 0
        error( ...
            'bmla:options:InvalidNameValuePairs', ...
            'Options must be supplied as NAME, VALUE pairs.');
    end

    validNames = string(fieldnames(options));

    for index = 1:2:nargin
        name = string(varargin{index});
        value = varargin{index + 1};

        match = find( ...
            strcmpi(name, validNames), ...
            1, ...
            'first');

        if isempty(match)
            error( ...
                'bmla:options:UnknownOption', ...
                'Unknown option "%s".', ...
                name);
        end

        canonicalName = char(validNames(match));
        options.(canonicalName) = value;
    end

    validate_options(options);
end


function validate_options(options)

    validateattributes( ...
        options.FunctionTolerance, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        'bmla.options', ...
        'FunctionTolerance');

    validateattributes( ...
        options.StepTolerance, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, ...
        'bmla.options', ...
        'StepTolerance');

    validateattributes( ...
        options.MaxIterations, ...
        {'numeric'}, ...
        {'scalar', 'real', 'finite', 'integer', 'positive'}, ...
        'bmla.options', ...
        'MaxIterations');

    displayValue = string(options.Display);

    if ~isscalar(displayValue) || ...
            ~any(strcmpi(displayValue, ["off", "final"]))

        error( ...
            'bmla:options:InvalidDisplay', ...
            'Display must be "off" or "final".');
    end

    if ~islogical(options.ReturnHistory) || ...
            ~isscalar(options.ReturnHistory)

        error( ...
            'bmla:options:InvalidReturnHistory', ...
            'ReturnHistory must be a logical scalar.');
    end

    options.Display = lower(displayValue); %#ok<NASGU>
end
