function [result, history] = bmla_v4_1_radius_consistent_solver(fun, x0, options)
%BMLA_V4_1_RADIUS_CONSISTENT_SOLVER Radius-consistent BMLA trust region.
%
% BMLA v4.1 preserves the frozen v3 local-affine architecture and the v4.0
% actual/predicted-reduction globalization. Its defining change is that the
% scale of the affine model is tied to the trust-region radius.
%
% At iteration k, candidate model samples satisfy
%
%   ||x_i - x_k||_2 <= gamma_model * Delta_k,
%
% and the regression uses normalized coordinates
%
%   z_i = (x_i - x_k)/Delta_k.
%
% If the local normalized displacements do not span R^n, geometry-restoring
% samples are evaluated along missing singular-vector directions. Finite
% rejected trials remain in the global sample archive but enter a model only
% when they are radius-local, nonduplicate, and selected by QR-maximin.
%
% The trust-region subproblem remains
%
%   min_h 0.5*||F(x_k) + A_k h||_2^2,  ||h||_2 <= Delta_k,
%
% with the same v4.0 acceptance, contraction, and expansion thresholds.
%
    arguments
        fun (1,1) function_handle
        x0 (:,1) double
        options struct
    end

    validate_options(options);

    xInitial = x0(:);
    numberOfVariables = numel(xInitial);

    initialScale = get_option( ...
        options, 'initialScale', 0.9);

    baseMemoryLength = get_option( ...
        options, 'memoryLength', numberOfVariables + 2);

    maxWindowLength = get_option( ...
        options, 'maxWindowLength', 3*(numberOfVariables + 2));

    maxConditionNumber = get_option( ...
        options, 'maxConditionNumber', 1e8);

    regularizationRelative = get_option( ...
        options, 'regularizationRelative', 1e-8);

    maxRelativeStep = get_option( ...
        options, 'maxRelativeStep', 1.0);

    stagnationPatience = get_option( ...
        options, 'stagnationPatience', 3);

    minimumRelativeResidualImprovement = get_option( ...
        options, ...
        'minimumRelativeResidualImprovement', ...
        1e-3);

    initialTrustRegionRelative = get_option( ...
        options, 'initialTrustRegionRelative', 0.50);

    minimumTrustRegionRelative = get_option( ...
        options, 'minimumTrustRegionRelative', 1e-10);

    maximumTrustRegionRelative = get_option( ...
        options, 'maximumTrustRegionRelative', 1.00);

    acceptanceThreshold = get_option( ...
        options, 'acceptanceThreshold', 0.10);

    shrinkThreshold = get_option( ...
        options, 'shrinkThreshold', 0.25);

    expansionThreshold = get_option( ...
        options, 'expansionThreshold', 0.75);

    radiusShrinkFactor = get_option( ...
        options, 'radiusShrinkFactor', 0.25);

    radiusExpansionFactor = get_option( ...
        options, 'radiusExpansionFactor', 2.00);

    boundaryFraction = get_option( ...
        options, 'boundaryFraction', 0.80);

    maximumConsecutiveRejectedTrials = get_option( ...
        options, ...
        'maximumConsecutiveRejectedTrials', ...
        12);

    minimumPredictedReductionRelative = get_option( ...
        options, ...
        'minimumPredictedReductionRelative', ...
        1e-12);


    localModelRadiusFactor = get_option( ...
        options, 'localModelRadiusFactor', 3.0);

    duplicateDistanceRelative = get_option( ...
        options, 'duplicateDistanceRelative', 1e-8);

    restorationStepFraction = get_option( ...
        options, 'restorationStepFraction', 0.80);

    maximumRestorationSamplesPerIteration = get_option( ...
        options, ...
        'maximumRestorationSamplesPerIteration', ...
        numberOfVariables);

    maximumGeometryRestorationRounds = get_option( ...
        options, ...
        'maximumGeometryRestorationRounds', ...
        2);

    maxFunctionEvaluations = get_option( ...
        options, ...
        'maxFunctionEvaluations', ...
        Inf);

    fInitial = fun(xInitial);
    fInitial = fInitial(:);

    functionEvaluations = 1;

    if any(~isfinite(xInitial)) || any(~isfinite(fInitial))
        error( ...
            'BMLAV4:InvalidInitialPoint', ...
            'The initial point or residual is nonfinite.');
    end

    sampleX = xInitial.';
    sampleF = fInitial.';

    history = initialize_v4_history( ...
        xInitial, fInitial, numberOfVariables);

    %% Coordinate initialization, preserving the v3 sampling pattern.

    initializationBudgetExhausted = false;

    for variableIndex = 1:numberOfVariables

        remainingFunctionEvaluations = ...
            maxFunctionEvaluations - functionEvaluations;

        if remainingFunctionEvaluations <= 0
            initializationBudgetExhausted = true;
            break;
        end

        requestedPerturbation = ...
            (initialScale - 1)*xInitial(variableIndex);

        if abs(requestedPerturbation) <= ...
                eps(max(1, abs(xInitial(variableIndex))))

            requestedPerturbation = ...
                -(1 - initialScale)* ...
                max(1, abs(xInitial(variableIndex)));
        end

        [xSample, fSample, actualPerturbation, ...
            initializationEvaluationCount, ...
            initializationSampleFound] = ...
            finite_initialization_sample( ...
                fun, ...
                xInitial, ...
                variableIndex, ...
                requestedPerturbation, ...
                remainingFunctionEvaluations);

        functionEvaluations = ...
            functionEvaluations + ...
            initializationEvaluationCount;

        if ~initializationSampleFound

            if functionEvaluations >= ...
                    maxFunctionEvaluations

                initializationBudgetExhausted = true;
                break;
            end

            error( ...
                'BMLAV41:InvalidInitializationSample', ...
                ['Unable to construct a finite initialization ' ...
                 'sample for variable %d.'], ...
                variableIndex);
        end

        sampleX(end + 1, :) = xSample.';
        sampleF(end + 1, :) = fSample.';

        previousPoint = history.x(:, end);
        initializationStep = xSample - previousPoint;

        history = append_initialization_history( ...
            history, ...
            xSample, ...
            fSample, ...
            initializationStep, ...
            functionEvaluations);
    end

    xCurrent = sampleX(end, :).';
    fCurrent = sampleF(end, :).';

    initialFunctionEvaluations = functionEvaluations;

    radiusScale = max(1, norm(xCurrent, 2));

    trustRegionRadius = ...
        initialTrustRegionRelative*radiusScale;

    minimumTrustRegionRadius = ...
        minimumTrustRegionRelative*radiusScale;

    maximumTrustRegionRadius = ...
        maximumTrustRegionRelative*radiusScale;

    trustRegionRadius = min( ...
        maximumTrustRegionRadius, ...
        max(minimumTrustRegionRadius, trustRegionRadius));

    converged = false;
    stopReason = "maximum_iterations";
    completedIterations = 0;

    stagnationCounter = 0;
    consecutiveRejectedTrials = 0;

    acceptedTrials = 0;
    rejectedTrials = 0;
    trustRegionShrinks = 0;
    trustRegionExpansions = 0;


    geometryRestorationSamples = 0;
    geometryRestorationEvaluations = 0;
    geometryRestorationIterations = 0;

    if norm(fCurrent, 2) < options.tolF
        converged = true;
        stopReason = "residual_tolerance";
    else

        for iteration = 1:options.maxIterations

            if functionEvaluations >= ...
                    maxFunctionEvaluations

                stopReason = ...
                    "maximum_function_evaluations";
                completedIterations = iteration - 1;
                break;
            end

            radiusScale = max(1, norm(xCurrent, 2));

            minimumTrustRegionRadius = ...
                minimumTrustRegionRelative*radiusScale;

            maximumTrustRegionRadius = ...
                maximumTrustRegionRelative*radiusScale;

            hardStepCap = ...
                maxRelativeStep*radiusScale;

            effectiveRadius = min( ...
                [ ...
                    trustRegionRadius, ...
                    maximumTrustRegionRadius, ...
                    hardStepCap ...
                ]);

            effectiveRadius = max( ...
                minimumTrustRegionRadius, ...
                effectiveRadius);

            [A, b, modelInfo, selectionInfo] = ...
                select_radius_consistent_local_model( ...
                    sampleX, ...
                    sampleF, ...
                    xCurrent, ...
                    effectiveRadius, ...
                    localModelRadiusFactor, ...
                    duplicateDistanceRelative, ...
                    baseMemoryLength, ...
                    maxWindowLength, ...
                    numberOfVariables, ...
                    maxConditionNumber);

            geometryRankBeforeRestoration = ...
                selectionInfo.geometryRank;

            restorationSamplesThisIteration = 0;
            restorationEvaluationsThisIteration = 0;
            restorationRoundsThisIteration = 0;

            while selectionInfo.needsGeometryRestoration && ...
                    restorationRoundsThisIteration < ...
                        maximumGeometryRestorationRounds

                [sampleX, sampleF, restorationInfo] = ...
                    restore_radius_consistent_geometry( ...
                        fun, ...
                        sampleX, ...
                        sampleF, ...
                        xCurrent, ...
                        effectiveRadius, ...
                        localModelRadiusFactor, ...
                        duplicateDistanceRelative, ...
                        maxWindowLength, ...
                        numberOfVariables, ...
                        restorationStepFraction, ...
                        maximumRestorationSamplesPerIteration, ...
                        maxFunctionEvaluations - ...
                            functionEvaluations);

                functionEvaluations = ...
                    functionEvaluations + ...
                    restorationInfo.functionEvaluations;

                restorationSamplesThisIteration = ...
                    restorationSamplesThisIteration + ...
                    restorationInfo.samplesAdded;

                restorationEvaluationsThisIteration = ...
                    restorationEvaluationsThisIteration + ...
                    restorationInfo.functionEvaluations;

                restorationRoundsThisIteration = ...
                    restorationRoundsThisIteration + 1;

                if restorationInfo.samplesAdded == 0
                    break;
                end

                [A, b, modelInfo, selectionInfo] = ...
                    select_radius_consistent_local_model( ...
                        sampleX, ...
                        sampleF, ...
                        xCurrent, ...
                        effectiveRadius, ...
                        localModelRadiusFactor, ...
                        duplicateDistanceRelative, ...
                        baseMemoryLength, ...
                        maxWindowLength, ...
                        numberOfVariables, ...
                        maxConditionNumber);
            end

            if restorationSamplesThisIteration > 0
                geometryRestorationIterations = ...
                    geometryRestorationIterations + 1;
            end

            geometryRestorationSamples = ...
                geometryRestorationSamples + ...
                restorationSamplesThisIteration;

            geometryRestorationEvaluations = ...
                geometryRestorationEvaluations + ...
                restorationEvaluationsThisIteration;

            selectionInfo.geometryRankBeforeRestoration = ...
                geometryRankBeforeRestoration;

            selectionInfo.restorationSamplesAdded = ...
                restorationSamplesThisIteration;

            selectionInfo.restorationFunctionEvaluations = ...
                restorationEvaluationsThisIteration;

            selectionInfo.restorationRounds = ...
                restorationRoundsThisIteration;

            if functionEvaluations >= ...
                    maxFunctionEvaluations

                stepInfo.lambda = NaN;
                stepInfo.usedRegularization = false;
                stepInfo.stepKind = ...
                    "function_evaluation_budget";
                stepInfo.predictedReduction = NaN;

                completedIterations = iteration;

                history = append_v4_iteration_history( ...
                    history, ...
                    xCurrent, ...
                    fCurrent, ...
                    zeros(numberOfVariables, 1), ...
                    functionEvaluations, ...
                    iteration, ...
                    modelInfo, ...
                    selectionInfo, ...
                    stepInfo, ...
                    trustRegionRadius, ...
                    effectiveRadius, ...
                    NaN, ...
                    NaN, ...
                    false, ...
                    stagnationCounter, ...
                    "function_evaluation_budget");

                stopReason = ...
                    "maximum_function_evaluations";
                break;
            end

            if isempty(A) || ...
                    any(~isfinite(A(:))) || ...
                    any(~isfinite(b))

                stopReason = "invalid_linear_model";
                break;
            end

            [step, stepInfo] = ...
                compute_affine_trust_region_step( ...
                    A, ...
                    fCurrent, ...
                    effectiveRadius, ...
                    selectionInfo.modelAccepted, ...
                    regularizationRelative, ...
                    minimumPredictedReductionRelative);

            if any(~isfinite(step)) || ...
                    stepInfo.predictedReduction <= 0

                trustRegionRadius = max( ...
                    minimumTrustRegionRadius, ...
                    radiusShrinkFactor*effectiveRadius);

                trustRegionShrinks = ...
                    trustRegionShrinks + 1;

                rejectedTrials = rejectedTrials + 1;
                consecutiveRejectedTrials = ...
                    consecutiveRejectedTrials + 1;

                completedIterations = iteration;

                history = append_v4_iteration_history( ...
                    history, ...
                    xCurrent, ...
                    fCurrent, ...
                    zeros(numberOfVariables, 1), ...
                    functionEvaluations, ...
                    iteration, ...
                    modelInfo, ...
                    selectionInfo, ...
                    stepInfo, ...
                    trustRegionRadius, ...
                    effectiveRadius, ...
                    -Inf, ...
                    -Inf, ...
                    false, ...
                    stagnationCounter, ...
                    "invalid_model_step");

                if consecutiveRejectedTrials >= ...
                        maximumConsecutiveRejectedTrials

                    stopReason = ...
                        "consecutive_rejected_trials";
                    break;
                end

                if trustRegionRadius <= ...
                        minimumTrustRegionRadius*(1 + 10*eps)

                    stopReason = "trust_region_too_small";
                    break;
                end

                continue;
            end

            if functionEvaluations >= ...
                    maxFunctionEvaluations

                stepInfo.stepKind = ...
                    "function_evaluation_budget";

                completedIterations = iteration;

                history = append_v4_iteration_history( ...
                    history, ...
                    xCurrent, ...
                    fCurrent, ...
                    zeros(numberOfVariables, 1), ...
                    functionEvaluations, ...
                    iteration, ...
                    modelInfo, ...
                    selectionInfo, ...
                    stepInfo, ...
                    trustRegionRadius, ...
                    effectiveRadius, ...
                    NaN, ...
                    NaN, ...
                    false, ...
                    stagnationCounter, ...
                    "function_evaluation_budget");

                stopReason = ...
                    "maximum_function_evaluations";
                break;
            end

            xTrial = xCurrent + step;
            fTrial = fun(xTrial);
            fTrial = fTrial(:);

            functionEvaluations = ...
                functionEvaluations + 1;

            trialFinite = ...
                all(isfinite(xTrial)) && ...
                all(isfinite(fTrial));

            currentMerit = 0.5*(fCurrent.'*fCurrent);

            predictedReduction = ...
                stepInfo.predictedReduction;

            if trialFinite

                trialMerit = 0.5*(fTrial.'*fTrial);
                actualReduction = ...
                    currentMerit - trialMerit;

                acceptanceRatio = ...
                    actualReduction / ...
                    predictedReduction;

            else

                actualReduction = -Inf;
                acceptanceRatio = -Inf;
            end

            acceptedTrial = ...
                trialFinite && ...
                actualReduction > 0 && ...
                acceptanceRatio >= ...
                    acceptanceThreshold;

            % Every finite expensive evaluation is useful model information,
            % even when the trust-region trial is rejected.
            if trialFinite
                sampleX(end + 1, :) = xTrial.';
                sampleF(end + 1, :) = fTrial.';
            end

            radiusBeforeUpdate = trustRegionRadius;

            if ~trialFinite || ...
                    acceptanceRatio < shrinkThreshold

                trustRegionRadius = max( ...
                    minimumTrustRegionRadius, ...
                    radiusShrinkFactor*effectiveRadius);

                trustRegionShrinks = ...
                    trustRegionShrinks + 1;

            elseif acceptedTrial && ...
                    acceptanceRatio > expansionThreshold && ...
                    norm(step, 2) >= ...
                        boundaryFraction*effectiveRadius

                trustRegionRadius = min( ...
                    maximumTrustRegionRadius, ...
                    radiusExpansionFactor* ...
                        trustRegionRadius);

                trustRegionExpansions = ...
                    trustRegionExpansions + 1;
            end

            if acceptedTrial

                [stop, reason, metrics, ...
                    stagnationCounter] = ...
                    evaluate_patient_stopping( ...
                        xCurrent, ...
                        xTrial, ...
                        fCurrent, ...
                        fTrial, ...
                        iteration, ...
                        options.tolX, ...
                        options.tolF, ...
                        options.maxIterations, ...
                        stagnationCounter, ...
                        stagnationPatience, ...
                        minimumRelativeResidualImprovement);

                xCurrent = xTrial;
                fCurrent = fTrial;

                acceptedTrials = acceptedTrials + 1;
                consecutiveRejectedTrials = 0;

                phaseLabel = "accepted_trial";

            else

                stop = false;
                reason = "continue";

                metrics.stepNorm = 0;
                metrics.smallStep = false;
                metrics.relativeResidualImprovement = NaN;
                metrics.productiveSmallStep = false;
                metrics.residualNorm = norm(fCurrent, 2);

                rejectedTrials = rejectedTrials + 1;
                consecutiveRejectedTrials = ...
                    consecutiveRejectedTrials + 1;

                phaseLabel = "rejected_trial";
            end

            history = append_v4_iteration_history( ...
                history, ...
                xCurrent, ...
                fCurrent, ...
                step, ...
                functionEvaluations, ...
                iteration, ...
                modelInfo, ...
                selectionInfo, ...
                stepInfo, ...
                trustRegionRadius, ...
                effectiveRadius, ...
                actualReduction, ...
                acceptanceRatio, ...
                acceptedTrial, ...
                stagnationCounter, ...
                phaseLabel);

            completedIterations = iteration;

            if acceptedTrial && stop
                stopReason = reason;
                converged = ...
                    reason == "residual_tolerance";
                break;
            end

            if ~acceptedTrial && ...
                    consecutiveRejectedTrials >= ...
                        maximumConsecutiveRejectedTrials

                stopReason = ...
                    "consecutive_rejected_trials";
                break;
            end

            if ~acceptedTrial && ...
                    trustRegionRadius <= ...
                        minimumTrustRegionRadius*(1 + 10*eps)

                stopReason = "trust_region_too_small";
                break;
            end

            if iteration >= options.maxIterations
                stopReason = "maximum_iterations";
            end
        end
    end

    finalRadiusScale = max(1, norm(xCurrent, 2));

    finalEffectiveRadius = min( ...
        [ ...
            trustRegionRadius, ...
            maximumTrustRegionRelative*finalRadiusScale, ...
            maxRelativeStep*finalRadiusScale ...
        ]);

    finalEffectiveRadius = max( ...
        minimumTrustRegionRelative*finalRadiusScale, ...
        finalEffectiveRadius);

    [finalA, finalB, finalModelInfo, ...
        finalSelectionInfo] = ...
        select_radius_consistent_local_model( ...
            sampleX, ...
            sampleF, ...
            xCurrent, ...
            finalEffectiveRadius, ...
            localModelRadiusFactor, ...
            duplicateDistanceRelative, ...
            baseMemoryLength, ...
            maxWindowLength, ...
            numberOfVariables, ...
            maxConditionNumber);

    result.x = xCurrent;
    result.f = fCurrent;
    result.normF = norm(fCurrent, 2);

    result.iterations = completedIterations;
    result.functionEvaluations = functionEvaluations;
    result.initialFunctionEvaluations = ...
        initialFunctionEvaluations;

    result.maxFunctionEvaluations = ...
        maxFunctionEvaluations;

    result.budgetExhausted = ...
        isfinite(maxFunctionEvaluations) && ...
        functionEvaluations >= ...
            maxFunctionEvaluations && ...
        stopReason == ...
            "maximum_function_evaluations";

    if isfinite(maxFunctionEvaluations)
        result.remainingFunctionEvaluations = max( ...
            0, ...
            maxFunctionEvaluations - ...
                functionEvaluations);
    else
        result.remainingFunctionEvaluations = Inf;
    end

    result.converged = converged;
    result.stopReason = stopReason;

    result.acceptedTrials = acceptedTrials;
    result.rejectedTrials = rejectedTrials;
    result.trustRegionShrinks = trustRegionShrinks;
    result.trustRegionExpansions = ...
        trustRegionExpansions;


    result.geometryRestorationSamples = ...
        geometryRestorationSamples;

    result.geometryRestorationEvaluations = ...
        geometryRestorationEvaluations;

    result.geometryRestorationIterations = ...
        geometryRestorationIterations;

    result.finalTrustRegionRadius = ...
        trustRegionRadius;

    result.regularizedIterations = ...
        sum(history.usedRegularization);

    result.cauchyIterations = ...
        sum(history.stepKind == "cauchy");

    finiteRatios = history.acceptanceRatio( ...
        isfinite(history.acceptanceRatio));

    if isempty(finiteRatios)
        result.meanAcceptanceRatio = NaN;
        result.medianAcceptanceRatio = NaN;
    else
        result.meanAcceptanceRatio = ...
            mean(finiteRatios);
        result.medianAcceptanceRatio = ...
            median(finiteRatios);
    end

    result.finalA = finalA;
    result.finalB = finalB;
    result.finalMatrixRank = ...
        finalModelInfo.matrixRank;
    result.finalConditionNumber = ...
        finalModelInfo.conditionNumber;
    result.finalModelResidual = ...
        finalModelInfo.residualNorm;
    result.finalPoolSize = ...
        finalSelectionInfo.poolSize;
    result.finalSelectedSamples = ...
        finalSelectionInfo.selectedSamples;


    result.finalModelRadius = ...
        finalSelectionInfo.modelRadius;

    result.finalNormalizationRadius = ...
        finalSelectionInfo.normalizationRadius;

    result.finalGeometryRank = ...
        finalSelectionInfo.geometryRank;

    result.finalLocalCandidateSamples = ...
        finalSelectionInfo.localCandidateSamples;

    result.maximumSelectedNormalizedDistance = ...
        max(history.maximumSelectedNormalizedDistance);

    result.allSelectedSamplesWithinModelRadius = ...
        all(history.allSelectedWithinModelRadius);

    result.allModelsContainedCurrentPoint = ...
        all(history.currentPointIncluded);

    result.maximumCurrentPointDistance = ...
        max(history.currentPointDistance);

    result.initialTrustRegionRelative = ...
        initialTrustRegionRelative;
    result.minimumTrustRegionRelative = ...
        minimumTrustRegionRelative;
    result.maximumTrustRegionRelative = ...
        maximumTrustRegionRelative;
    result.acceptanceThreshold = ...
        acceptanceThreshold;
    result.shrinkThreshold = shrinkThreshold;
    result.expansionThreshold = expansionThreshold;
    result.radiusShrinkFactor = ...
        radiusShrinkFactor;
    result.radiusExpansionFactor = ...
        radiusExpansionFactor;
    result.maximumConsecutiveRejectedTrials = ...
        maximumConsecutiveRejectedTrials;

    result.localModelRadiusFactor = ...
        localModelRadiusFactor;

    result.duplicateDistanceRelative = ...
        duplicateDistanceRelative;

    result.restorationStepFraction = ...
        restorationStepFraction;

    result.maximumRestorationSamplesPerIteration = ...
        maximumRestorationSamplesPerIteration;

    result.maximumGeometryRestorationRounds = ...
        maximumGeometryRestorationRounds;
end


function history = initialize_v4_history( ...
        xInitial, fInitial, numberOfVariables)
%INITIALIZE_V4_HISTORY

    history.x = xInitial;
    history.f = fInitial;
    history.normF = norm(fInitial, 2);

    history.step = zeros(numberOfVariables, 1);
    history.stepNorm = 0;

    history.matrixRank = NaN;
    history.conditionNumber = NaN;
    history.designMatrixRank = NaN;
    history.designConditionNumber = NaN;
    history.modelResidual = NaN;

    history.poolSize = NaN;
    history.selectedSamples = NaN;
    history.selectionExpansion = NaN;
    history.modelAccepted = false;
    history.currentPointIncluded = true;
    history.currentPointDistance = 0;

    history.modelRadius = NaN;
    history.normalizationRadius = NaN;
    history.localCandidateSamples = NaN;
    history.uniqueLocalSamples = NaN;
    history.geometryRank = NaN;
    history.geometryRankBeforeRestoration = NaN;
    history.maximumSelectedNormalizedDistance = 0;
    history.allSelectedWithinModelRadius = true;
    history.restorationSamplesAdded = 0;
    history.restorationFunctionEvaluations = 0;
    history.restorationRounds = 0;

    history.usedRegularization = false;
    history.regularizationLambda = NaN;
    history.stepKind = "initial";

    history.trustRegionRadius = NaN;
    history.effectiveRadius = NaN;
    history.predictedReduction = NaN;
    history.actualReduction = NaN;
    history.acceptanceRatio = NaN;
    history.acceptedTrial = false;

    history.stagnationCounter = 0;
    history.iteration = 0;
    history.functionEvaluations = 1;
    history.phase = "initial";
end


function history = append_initialization_history( ...
        history, xSample, fSample, step, functionEvaluations)
%APPEND_INITIALIZATION_HISTORY

    history.x(:, end + 1) = xSample;
    history.f(:, end + 1) = fSample;
    history.normF(end + 1) = norm(fSample, 2);

    history.step(:, end + 1) = step;
    history.stepNorm(end + 1) = norm(step, 2);

    history.matrixRank(end + 1) = NaN;
    history.conditionNumber(end + 1) = NaN;
    history.designMatrixRank(end + 1) = NaN;
    history.designConditionNumber(end + 1) = NaN;
    history.modelResidual(end + 1) = NaN;

    history.poolSize(end + 1) = NaN;
    history.selectedSamples(end + 1) = NaN;
    history.selectionExpansion(end + 1) = NaN;
    history.modelAccepted(end + 1) = false;
    history.currentPointIncluded(end + 1) = true;
    history.currentPointDistance(end + 1) = 0;

    history.modelRadius(end + 1) = NaN;
    history.normalizationRadius(end + 1) = NaN;
    history.localCandidateSamples(end + 1) = NaN;
    history.uniqueLocalSamples(end + 1) = NaN;
    history.geometryRank(end + 1) = NaN;
    history.geometryRankBeforeRestoration(end + 1) = NaN;
    history.maximumSelectedNormalizedDistance(end + 1) = 0;
    history.allSelectedWithinModelRadius(end + 1) = true;
    history.restorationSamplesAdded(end + 1) = 0;
    history.restorationFunctionEvaluations(end + 1) = 0;
    history.restorationRounds(end + 1) = 0;

    history.usedRegularization(end + 1) = false;
    history.regularizationLambda(end + 1) = NaN;
    history.stepKind(end + 1) = "initialization";

    history.trustRegionRadius(end + 1) = NaN;
    history.effectiveRadius(end + 1) = NaN;
    history.predictedReduction(end + 1) = NaN;
    history.actualReduction(end + 1) = NaN;
    history.acceptanceRatio(end + 1) = NaN;
    history.acceptedTrial(end + 1) = false;

    history.stagnationCounter(end + 1) = 0;
    history.iteration(end + 1) = 0;
    history.functionEvaluations(end + 1) = ...
        functionEvaluations;
    history.phase(end + 1) = "initialization";
end


function history = append_v4_iteration_history( ...
        history, xCurrent, fCurrent, step, ...
        functionEvaluations, iteration, ...
        modelInfo, selectionInfo, stepInfo, ...
        trustRegionRadius, effectiveRadius, ...
        actualReduction, acceptanceRatio, ...
        acceptedTrial, stagnationCounter, phaseLabel)
%APPEND_V4_ITERATION_HISTORY

    history.x(:, end + 1) = xCurrent;
    history.f(:, end + 1) = fCurrent;
    history.normF(end + 1) = norm(fCurrent, 2);

    history.step(:, end + 1) = step;
    history.stepNorm(end + 1) = norm(step, 2);

    history.matrixRank(end + 1) = ...
        modelInfo.matrixRank;
    history.conditionNumber(end + 1) = ...
        modelInfo.conditionNumber;
    history.designMatrixRank(end + 1) = ...
        modelInfo.designMatrixRank;
    history.designConditionNumber(end + 1) = ...
        modelInfo.designConditionNumber;
    history.modelResidual(end + 1) = ...
        modelInfo.residualNorm;

    history.poolSize(end + 1) = ...
        selectionInfo.poolSize;
    history.selectedSamples(end + 1) = ...
        selectionInfo.selectedSamples;
    history.selectionExpansion(end + 1) = ...
        selectionInfo.selectionExpansion;
    history.modelAccepted(end + 1) = ...
        selectionInfo.modelAccepted;
    history.currentPointIncluded(end + 1) = ...
        selectionInfo.currentPointIncluded;
    history.currentPointDistance(end + 1) = ...
        selectionInfo.currentPointDistance;

    history.modelRadius(end + 1) = ...
        selectionInfo.modelRadius;
    history.normalizationRadius(end + 1) = ...
        selectionInfo.normalizationRadius;
    history.localCandidateSamples(end + 1) = ...
        selectionInfo.localCandidateSamples;
    history.uniqueLocalSamples(end + 1) = ...
        selectionInfo.uniqueLocalSamples;
    history.geometryRank(end + 1) = ...
        selectionInfo.geometryRank;
    history.geometryRankBeforeRestoration(end + 1) = ...
        selectionInfo.geometryRankBeforeRestoration;
    history.maximumSelectedNormalizedDistance(end + 1) = ...
        selectionInfo.maximumSelectedNormalizedDistance;
    history.allSelectedWithinModelRadius(end + 1) = ...
        selectionInfo.allSelectedWithinModelRadius;
    history.restorationSamplesAdded(end + 1) = ...
        selectionInfo.restorationSamplesAdded;
    history.restorationFunctionEvaluations(end + 1) = ...
        selectionInfo.restorationFunctionEvaluations;
    history.restorationRounds(end + 1) = ...
        selectionInfo.restorationRounds;

    history.usedRegularization(end + 1) = ...
        stepInfo.usedRegularization;
    history.regularizationLambda(end + 1) = ...
        stepInfo.lambda;
    history.stepKind(end + 1) = ...
        stepInfo.stepKind;

    history.trustRegionRadius(end + 1) = ...
        trustRegionRadius;
    history.effectiveRadius(end + 1) = ...
        effectiveRadius;
    history.predictedReduction(end + 1) = ...
        stepInfo.predictedReduction;
    history.actualReduction(end + 1) = ...
        actualReduction;
    history.acceptanceRatio(end + 1) = ...
        acceptanceRatio;
    history.acceptedTrial(end + 1) = ...
        acceptedTrial;

    history.stagnationCounter(end + 1) = ...
        stagnationCounter;
    history.iteration(end + 1) = iteration;
    history.functionEvaluations(end + 1) = ...
        functionEvaluations;
    history.phase(end + 1) = string(phaseLabel);
end


function [xSample, fSample, actualPerturbation, ...
        evaluationCount, success] = ...
        finite_initialization_sample( ...
            fun, xInitial, variableIndex, ...
            requestedPerturbation, ...
            maximumEvaluations)
%FINITE_INITIALIZATION_SAMPLE Back off only when initialization overflows.
%
% Every attempted residual evaluation is counted. The routine never exceeds
% maximumEvaluations and reports success explicitly.

    actualPerturbation = requestedPerturbation;
    evaluationCount = 0;
    success = false;

    xSample = xInitial;
    fSample = NaN(size(xInitial));

    maximumAttempts = min( ...
        24, ...
        floor(maximumEvaluations));

    for attempt = 1:maximumAttempts

        xSample = xInitial;
        xSample(variableIndex) = ...
            xInitial(variableIndex) + ...
            actualPerturbation;

        fSample = fun(xSample);
        fSample = fSample(:);

        evaluationCount = ...
            evaluationCount + 1;

        if all(isfinite(xSample)) && ...
                all(isfinite(fSample))

            success = true;
            return;
        end

        actualPerturbation = ...
            0.5*actualPerturbation;
    end
end


function [step, info] = ...
        compute_affine_trust_region_step( ...
            A, fCurrent, trustRadius, ...
            modelAccepted, regularizationRelative, ...
            minimumPredictedReductionRelative)
%COMPUTE_AFFINE_TRUST_REGION_STEP
%
% Solve the linear least-squares trust-region subproblem through the SVD:
%
%   min 0.5*||f + A h||^2,  ||h|| <= Delta.
%
% A Levenberg-Marquardt multiplier is found by bracketing and bisection.
% If numerical cancellation makes the predicted reduction nonpositive, a
% Cauchy step for the same model is used.

    numberOfVariables = size(A, 2);

    [U, S, V] = svd(A, 'econ');
    singularValues = diag(S);

    if isempty(singularValues)
        step = zeros(numberOfVariables, 1);
        info.lambda = NaN;
        info.usedRegularization = true;
        info.stepKind = "invalid";
        info.predictedReduction = -Inf;
        return;
    end

    matrixTolerance = ...
        max(size(A))*eps(max(singularValues));

    fullRank = ...
        sum(singularValues > matrixTolerance) >= ...
        numberOfVariables;

    if modelAccepted && fullRank
        lambdaFloor = 0;
    else
        lambdaFloor = ...
            regularizationRelative* ...
            max(singularValues(1)^2, 1);
    end

    [stepAtFloor, floorNorm] = ...
        lm_step_from_svd( ...
            U, singularValues, V, ...
            fCurrent, lambdaFloor, ...
            matrixTolerance);

    lambda = lambdaFloor;

    if floorNorm > trustRadius

        lambdaLow = lambdaFloor;
        lambdaHigh = max( ...
            [ ...
                1e-16, ...
                regularizationRelative* ...
                    max(singularValues(1)^2, 1), ...
                lambdaFloor ...
            ]);

        [stepHigh, highNorm] = ...
            lm_step_from_svd( ...
                U, singularValues, V, ...
                fCurrent, lambdaHigh, ...
                matrixTolerance);

        expansionCounter = 0;

        while highNorm > trustRadius && ...
                expansionCounter < 80

            lambdaHigh = max( ...
                2*lambdaHigh, ...
                lambdaHigh + 1e-16);

            [stepHigh, highNorm] = ...
                lm_step_from_svd( ...
                    U, singularValues, V, ...
                    fCurrent, lambdaHigh, ...
                    matrixTolerance);

            expansionCounter = ...
                expansionCounter + 1;
        end

        if highNorm > trustRadius

            step = ...
                trustRadius* ...
                stepHigh/max(highNorm, eps);

            lambda = lambdaHigh;

        else

            for bisectionIndex = 1:60

                lambdaMid = ...
                    0.5*(lambdaLow + lambdaHigh);

                [stepMid, midNorm] = ...
                    lm_step_from_svd( ...
                        U, singularValues, V, ...
                        fCurrent, lambdaMid, ...
                        matrixTolerance);

                if midNorm > trustRadius
                    lambdaLow = lambdaMid;
                else
                    lambdaHigh = lambdaMid;
                    stepHigh = stepMid;
                end
            end

            step = stepHigh;
            lambda = lambdaHigh;
        end

    else

        step = stepAtFloor;
    end

    modelResidual = fCurrent + A*step;

    currentMerit = 0.5*(fCurrent.'*fCurrent);
    modelMerit = 0.5*(modelResidual.'*modelResidual);

    predictedReduction = ...
        currentMerit - modelMerit;

    minimumPredictedReduction = ...
        minimumPredictedReductionRelative* ...
        max(currentMerit, eps);

    stepKind = "newton";

    if lambda > 0
        stepKind = "levenberg_marquardt";
    end

    if ~isfinite(predictedReduction) || ...
            predictedReduction <= ...
                minimumPredictedReduction

        gradient = A.'*fCurrent;
        gradientNorm = norm(gradient, 2);

        if gradientNorm == 0 || ...
                ~isfinite(gradientNorm)

            step = zeros(numberOfVariables, 1);
            predictedReduction = -Inf;
            stepKind = "invalid";

        else

            AGradient = A*gradient;
            denominator = AGradient.'*AGradient;
            numerator = gradient.'*gradient;

            if denominator > 0 && isfinite(denominator)
                alpha = numerator/denominator;
            else
                alpha = trustRadius/gradientNorm;
            end

            alpha = min( ...
                alpha, ...
                trustRadius/gradientNorm);

            step = -alpha*gradient;

            modelResidual = fCurrent + A*step;

            predictedReduction = ...
                currentMerit - ...
                0.5*(modelResidual.'*modelResidual);

            stepKind = "cauchy";
            lambda = NaN;
        end
    end

    info.lambda = lambda;
    info.usedRegularization = ...
        stepKind == "levenberg_marquardt";
    info.stepKind = stepKind;
    info.predictedReduction = ...
        predictedReduction;
end


function [step, stepNorm] = ...
        lm_step_from_svd( ...
            U, singularValues, V, ...
            fCurrent, lambda, matrixTolerance)
%LM_STEP_FROM_SVD Stable LM step for a fixed multiplier.

    projectedResidual = U.'*fCurrent;

    weights = zeros(size(singularValues));

    active = ...
        singularValues > matrixTolerance;

    if lambda > 0
        weights = ...
            singularValues ./ ...
            (singularValues.^2 + lambda);
    else
        weights(active) = ...
            1 ./ singularValues(active);
    end

    step = -V*(weights.*projectedResidual);
    stepNorm = norm(step, 2);
end




function [stop, reason, metrics, newCounter] = ...
        evaluate_patient_stopping( ...
            xCurrent, xNext, fCurrent, fNext, iteration, ...
            tolX, tolF, maxIterations, ...
            currentCounter, stagnationPatience, ...
            minimumRelativeResidualImprovement)
%EVALUATE_PATIENT_STOPPING
% Aplica convergencia residual estricta y estancamiento paciente.

    metrics.stepNorm = norm( ...
        xNext - xCurrent, ...
        2);

    metrics.xNorm = norm(xCurrent, 2);

    metrics.residualNorm = norm(fNext, 2);

    metrics.previousResidualNorm = ...
        norm(fCurrent, 2);

    metrics.stepThreshold = ...
        tolX*(metrics.xNorm + tolX);

    metrics.smallStep = ...
        metrics.stepNorm <= ...
        metrics.stepThreshold;

    metrics.relativeResidualImprovement = ...
        (metrics.previousResidualNorm - ...
         metrics.residualNorm) / ...
        max(metrics.previousResidualNorm, eps);

    metrics.productiveSmallStep = ...
        metrics.smallStep && ...
        metrics.relativeResidualImprovement >= ...
        minimumRelativeResidualImprovement;

    numericalFailure = ...
        any(~isfinite(xNext)) || ...
        any(~isfinite(fNext));

    residualSatisfied = ...
        metrics.residualNorm < tolF;

    stop = false;
    reason = "continue";

    if numericalFailure

        newCounter = currentCounter;
        stop = true;
        reason = "numerical_failure";
        return;
    end

    if residualSatisfied

        newCounter = 0;
        stop = true;
        reason = "residual_tolerance";
        return;
    end

    if metrics.smallStep

        if metrics.productiveSmallStep

            newCounter = 0;

        else

            newCounter = ...
                currentCounter + 1;
        end

    else

        newCounter = 0;
    end

    if newCounter >= stagnationPatience

        stop = true;
        reason = "stagnation";
        return;
    end

    if iteration >= maxIterations

        stop = true;
        reason = "maximum_iterations";
    end
end


function [sampleX, sampleF, info] = ...
        restore_radius_consistent_geometry( ...
            fun, sampleX, sampleF, xCurrent, ...
            effectiveRadius, localModelRadiusFactor, ...
            duplicateDistanceRelative, maxWindowLength, ...
            numberOfVariables, restorationStepFraction, ...
            maximumRestorationSamples, ...
            maximumFunctionEvaluations)
%RESTORE_RADIUS_CONSISTENT_GEOMETRY Add samples in missing local directions.

    normalizationRadius = max( ...
        effectiveRadius, ...
        100*eps(max(1, norm(xCurrent, 2))));

    modelRadius = ...
        localModelRadiusFactor*normalizationRadius;

    [localIndices, currentGlobalIndex] = ...
        radius_local_unique_indices( ...
            sampleX, ...
            xCurrent, ...
            modelRadius, ...
            normalizationRadius, ...
            duplicateDistanceRelative, ...
            maxWindowLength);

    localX = sampleX(localIndices, :);
    localZ = ...
        (localX - xCurrent.')/normalizationRadius;

    currentLocalIndex = find( ...
        localIndices == currentGlobalIndex, ...
        1, ...
        'last');

    displacementRows = localZ;
    displacementRows(currentLocalIndex, :) = [];

    [geometryRank, rightSingularVectors] = ...
        normalized_geometry_rank( ...
            displacementRows, ...
            numberOfVariables);

    missingDirections = ...
        rightSingularVectors(:, ...
            geometryRank + 1:numberOfVariables);

    numberRequested = min( ...
        [ ...
            size(missingDirections, 2), ...
            maximumRestorationSamples ...
        ]);

    samplesAdded = 0;
    functionEvaluations = 0;
    failedDirections = 0;

    baseStepLength = ...
        restorationStepFraction*normalizationRadius;

    for directionIndex = 1:numberRequested

        remainingFunctionEvaluations = ...
            maximumFunctionEvaluations - ...
            functionEvaluations;

        if remainingFunctionEvaluations <= 0
            break;
        end

        direction = ...
            missingDirections(:, directionIndex);

        [xSample, fSample, evaluationCount, success] = ...
            finite_restoration_sample( ...
                fun, ...
                xCurrent, ...
                direction, ...
                baseStepLength, ...
                sampleX, ...
                normalizationRadius, ...
                duplicateDistanceRelative, ...
                remainingFunctionEvaluations);

        functionEvaluations = ...
            functionEvaluations + evaluationCount;

        if success
            sampleX(end + 1, :) = xSample.';
            sampleF(end + 1, :) = fSample.';
            samplesAdded = samplesAdded + 1;
        else
            failedDirections = failedDirections + 1;
        end
    end

    [updatedIndices, ~] = ...
        radius_local_unique_indices( ...
            sampleX, ...
            xCurrent, ...
            modelRadius, ...
            normalizationRadius, ...
            duplicateDistanceRelative, ...
            maxWindowLength);

    updatedZ = ...
        (sampleX(updatedIndices, :) - ...
         xCurrent.')/normalizationRadius;

    updatedDistances = vecnorm(updatedZ, 2, 2);
    currentTolerance = ...
        100*eps(max(1, norm(xCurrent, 2)))/ ...
        normalizationRadius;

    updatedDisplacements = ...
        updatedZ(updatedDistances > currentTolerance, :);

    [finalGeometryRank, ~] = ...
        normalized_geometry_rank( ...
            updatedDisplacements, ...
            numberOfVariables);

    info.samplesAdded = samplesAdded;
    info.functionEvaluations = functionEvaluations;
    info.failedDirections = failedDirections;
    info.initialGeometryRank = geometryRank;
    info.finalGeometryRank = finalGeometryRank;
    info.modelRadius = modelRadius;
    info.normalizationRadius = normalizationRadius;
    info.budgetExhausted = ...
        isfinite(maximumFunctionEvaluations) && ...
        functionEvaluations >= ...
            maximumFunctionEvaluations;
end


function [xSample, fSample, evaluationCount, success] = ...
        finite_restoration_sample( ...
            fun, xCurrent, direction, requestedStepLength, ...
            sampleX, normalizationRadius, ...
            duplicateDistanceRelative, ...
            maximumEvaluations)
%FINITE_RESTORATION_SAMPLE Try both signs and geometric backoff.

    directionNorm = norm(direction, 2);

    if directionNorm == 0 || ~isfinite(directionNorm)
        xSample = xCurrent;
        fSample = NaN(size(xCurrent));
        evaluationCount = 0;
        success = false;
        return;
    end

    direction = direction/directionNorm;
    stepLength = requestedStepLength;
    evaluationCount = 0;
    success = false;

    xSample = xCurrent;
    fSample = NaN(size(xCurrent));

    for backoffIndex = 1:12

        for signValue = [1, -1]

            candidate = ...
                xCurrent + ...
                signValue*stepLength*direction;

            normalizedDistances = vecnorm( ...
                (sampleX - candidate.')/ ...
                normalizationRadius, ...
                2, ...
                2);

            if any(normalizedDistances <= ...
                    duplicateDistanceRelative)
                continue;
            end

            if evaluationCount >= ...
                    maximumEvaluations
                return;
            end

            candidateResidual = fun(candidate);
            candidateResidual = candidateResidual(:);
            evaluationCount = evaluationCount + 1;

            if all(isfinite(candidate)) && ...
                    all(isfinite(candidateResidual))

                xSample = candidate;
                fSample = candidateResidual;
                success = true;
                return;
            end
        end

        stepLength = 0.5*stepLength;
    end
end


function [A, b, modelInfo, selectionInfo] = ...
        select_radius_consistent_local_model( ...
            sampleX, sampleF, xCurrent, ...
            effectiveRadius, localModelRadiusFactor, ...
            duplicateDistanceRelative, ...
            baseMemoryLength, maxWindowLength, ...
            numberOfVariables, maxConditionNumber)
%SELECT_RADIUS_CONSISTENT_LOCAL_MODEL Build a Delta-scaled local model.

    normalizationRadius = max( ...
        effectiveRadius, ...
        100*eps(max(1, norm(xCurrent, 2))));

    modelRadius = ...
        localModelRadiusFactor*normalizationRadius;

    [poolIndices, currentGlobalIndex, localCandidateSamples] = ...
        radius_local_unique_indices( ...
            sampleX, ...
            xCurrent, ...
            modelRadius, ...
            normalizationRadius, ...
            duplicateDistanceRelative, ...
            maxWindowLength);

    poolX = sampleX(poolIndices, :);
    poolF = sampleF(poolIndices, :);
    poolZ = ...
        (poolX - xCurrent.')/normalizationRadius;

    poolSize = size(poolX, 1);

    currentLocalIndex = find( ...
        poolIndices == currentGlobalIndex, ...
        1, ...
        'last');

    geometryRows = poolZ;
    geometryRows(currentLocalIndex, :) = [];

    [geometryRank, ~] = ...
        normalized_geometry_rank( ...
            geometryRows, ...
            numberOfVariables);

    needsGeometryRestoration = ...
        (geometryRank < numberOfVariables) || ...
        (poolSize < numberOfVariables + 1);

    minimumSelectedSamples = min( ...
        poolSize, ...
        max( ...
            numberOfVariables + 1, ...
            baseMemoryLength));

    bestRank = -Inf;
    bestConditionScore = -Inf;

    bestA = zeros(numberOfVariables);
    bestB = sampleF(currentGlobalIndex, :).';
    bestModelInfo = empty_radius_model_info( ...
        numberOfVariables, normalizationRadius);
    bestSelectedSamples = 1;
    bestSelectedIndices = currentLocalIndex;

    modelAccepted = false;

    for selectedSamples = ...
            minimumSelectedSamples:poolSize

        selectedIndices = ...
            select_radius_informative_indices( ...
                poolZ, ...
                currentLocalIndex, ...
                selectedSamples, ...
                numberOfVariables);

        localX = poolX(selectedIndices, :);
        localF = poolF(selectedIndices, :);

        [candidateA, candidateB, ...
            candidateModelInfo] = ...
            fit_radius_normalized_affine_model( ...
                localX, ...
                localF, ...
                xCurrent, ...
                normalizationRadius, ...
                numberOfVariables);

        designAccepted = ...
            candidateModelInfo.designMatrixRank >= ...
            numberOfVariables + 1;

        rankAccepted = ...
            candidateModelInfo.matrixRank >= ...
            numberOfVariables;

        conditionAccepted = ...
            isfinite( ...
                candidateModelInfo.conditionNumber) && ...
            candidateModelInfo.conditionNumber <= ...
                maxConditionNumber;

        candidateAccepted = ...
            designAccepted && ...
            rankAccepted && ...
            conditionAccepted;

        candidateRank = ...
            candidateModelInfo.matrixRank;

        candidateConditionScore = ...
            -log10(max( ...
                candidateModelInfo.conditionNumber, ...
                1));

        if candidateRank > bestRank || ...
                (candidateRank == bestRank && ...
                 candidateConditionScore > ...
                 bestConditionScore)

            bestRank = candidateRank;
            bestConditionScore = ...
                candidateConditionScore;

            bestA = candidateA;
            bestB = candidateB;
            bestModelInfo = ...
                candidateModelInfo;

            bestSelectedSamples = ...
                selectedSamples;

            bestSelectedIndices = ...
                selectedIndices;
        end

        if candidateAccepted

            A = candidateA;
            b = candidateB;
            modelInfo = candidateModelInfo;

            modelAccepted = true;
            bestSelectedSamples = ...
                selectedSamples;
            bestSelectedIndices = ...
                selectedIndices;

            break;
        end
    end

    if ~modelAccepted
        A = bestA;
        b = bestB;
        modelInfo = bestModelInfo;
    end

    selectedNormalizedDistances = vecnorm( ...
        poolZ(bestSelectedIndices, :), ...
        2, ...
        2);

    if isempty(selectedNormalizedDistances)
        maximumSelectedNormalizedDistance = 0;
    else
        maximumSelectedNormalizedDistance = ...
            max(selectedNormalizedDistances);
    end

    currentDistance = norm( ...
        sampleX(currentGlobalIndex, :).' - ...
        xCurrent, ...
        2);

    selectionInfo.poolStartIndex = ...
        min(poolIndices);
    selectionInfo.poolEndIndex = ...
        max(poolIndices);
    selectionInfo.poolSize = poolSize;
    selectionInfo.localCandidateSamples = ...
        localCandidateSamples;
    selectionInfo.uniqueLocalSamples = ...
        poolSize;
    selectionInfo.currentPointIncluded = ...
        ismember(currentGlobalIndex, poolIndices);
    selectionInfo.currentPointDistance = ...
        currentDistance;
    selectionInfo.selectedSamples = ...
        bestSelectedSamples;
    selectionInfo.selectionExpansion = ...
        max( ...
            0, ...
            bestSelectedSamples - ...
            minimumSelectedSamples);
    selectionInfo.modelAccepted = ...
        modelAccepted;
    selectionInfo.geometryRank = ...
        geometryRank;
    selectionInfo.needsGeometryRestoration = ...
        needsGeometryRestoration;
    selectionInfo.modelRadius = ...
        modelRadius;
    selectionInfo.normalizationRadius = ...
        normalizationRadius;
    selectionInfo.maximumSelectedNormalizedDistance = ...
        maximumSelectedNormalizedDistance;
    selectionInfo.allSelectedWithinModelRadius = ...
        maximumSelectedNormalizedDistance <= ...
        localModelRadiusFactor*(1 + 100*eps);

    selectionInfo.geometryRankBeforeRestoration = ...
        geometryRank;
    selectionInfo.restorationSamplesAdded = 0;
    selectionInfo.restorationFunctionEvaluations = 0;
    selectionInfo.restorationRounds = 0;
end


function [poolIndices, currentGlobalIndex, localCandidateSamples] = ...
        radius_local_unique_indices( ...
            sampleX, xCurrent, modelRadius, ...
            normalizationRadius, duplicateDistanceRelative, ...
            maxWindowLength)
%RADIUS_LOCAL_UNIQUE_INDICES Recent, radius-local, nonduplicate samples.

    numberOfSamples = size(sampleX, 1);

    poolStartIndex = max( ...
        1, ...
        numberOfSamples - ...
        maxWindowLength + 1);

    recentIndices = ...
        (poolStartIndex:numberOfSamples).';

    allDistances = vecnorm( ...
        sampleX - xCurrent.', ...
        2, ...
        2);

    minimumDistance = min(allDistances);

    currentTolerance = ...
        100*eps(max(1, norm(xCurrent, 2)));

    currentCandidates = find( ...
        allDistances <= ...
        minimumDistance + currentTolerance);

    currentGlobalIndex = ...
        currentCandidates(end);

    radiusTolerance = ...
        100*eps(max(1, modelRadius));

    localRecentIndices = recentIndices( ...
        allDistances(recentIndices) <= ...
        modelRadius + radiusTolerance);

    localCandidateSamples = ...
        numel(localRecentIndices);

    candidateOrder = [ ...
        currentGlobalIndex; ...
        flipud(setdiff( ...
            localRecentIndices, ...
            currentGlobalIndex, ...
            'stable')) ...
    ];

    keptIndices = currentGlobalIndex;
    keptNormalizedCoordinates = zeros(1, size(sampleX, 2));

    % Use an explicit scalar index instead of transposing candidateOrder.
    % For a singleton candidateOrder, candidateOrder(2:end).' can become a
    % 0-by-1 matrix. MATLAB then executes one loop iteration with an empty
    % loop variable, which caused the assignment failure found by the first
    % v4.1 smoke test.
    candidateOrder = candidateOrder(:);

    for orderPosition = 2:numel(candidateOrder)

        candidateIndex = ...
            candidateOrder(orderPosition);

        candidateNormalized = ...
            (sampleX(candidateIndex, :) - ...
             xCurrent.')/normalizationRadius;

        distancesToKept = vecnorm( ...
            keptNormalizedCoordinates - ...
            candidateNormalized, ...
            2, ...
            2);

        if all(distancesToKept > ...
                duplicateDistanceRelative)

            keptIndices(end + 1, 1) = ...
                candidateIndex;

            keptNormalizedCoordinates(end + 1, :) = ...
                candidateNormalized;
        end
    end

    poolIndices = keptIndices;
end


function selectedIndices = ...
        select_radius_informative_indices( ...
            poolZ, referenceIndex, ...
            selectedSamples, numberOfVariables)
%SELECT_RADIUS_INFORMATIVE_INDICES QR-maximin in Delta-normalized space.

    poolSize = size(poolZ, 1);

    selectedSamples = min( ...
        selectedSamples, ...
        poolSize);

    if selectedSamples == 1
        selectedIndices = referenceIndex;
        return;
    end

    candidateIndices = setdiff( ...
        (1:poolSize).', ...
        referenceIndex, ...
        'stable');

    normalizedDifferences = ...
        poolZ(candidateIndices, :) - ...
        poolZ(referenceIndex, :);

    numberRequiredBeforeReference = ...
        selectedSamples - 1;

    selectedCandidatePositions = ...
        zeros(0, 1);

    if ~isempty(normalizedDifferences)

        try
            [~, ~, pivotOrder] = ...
                qr( ...
                    normalizedDifferences.', ...
                    'vector');
        catch
            [~, ~, permutationMatrix] = ...
                qr(normalizedDifferences.');
            [~, pivotOrder] = ...
                max(permutationMatrix, [], 1);
        end

        numberOfQRPicks = min( ...
            [ ...
                numberOfVariables, ...
                numberRequiredBeforeReference, ...
                numel(pivotOrder) ...
            ]);

        selectedCandidatePositions = ...
            pivotOrder(1:numberOfQRPicks).';
    end

    allCandidatePositions = ...
        (1:numel(candidateIndices)).';

    while numel(selectedCandidatePositions) < ...
            numberRequiredBeforeReference

        availablePositions = setdiff( ...
            allCandidatePositions, ...
            selectedCandidatePositions, ...
            'stable');

        if isempty(availablePositions)
            break;
        end

        selectedCoordinates = ...
            poolZ(referenceIndex, :);

        if ~isempty(selectedCandidatePositions)
            selectedCoordinates = [ ...
                selectedCoordinates
                poolZ( ...
                    candidateIndices( ...
                        selectedCandidatePositions), :) ...
            ];
        end

        bestPosition = ...
            availablePositions(1);
        bestMinimumDistance = -Inf;

        for candidatePosition = ...
                availablePositions.'

            candidateCoordinates = ...
                poolZ( ...
                    candidateIndices(candidatePosition), :);

            distances = vecnorm( ...
                selectedCoordinates - ...
                candidateCoordinates, ...
                2, ...
                2);

            candidateMinimumDistance = ...
                min(distances);

            if candidateMinimumDistance > ...
                    bestMinimumDistance

                bestMinimumDistance = ...
                    candidateMinimumDistance;
                bestPosition = ...
                    candidatePosition;
            end
        end

        selectedCandidatePositions(end + 1, 1) = ...
            bestPosition;
    end

    selectedIndices = [ ...
        candidateIndices( ...
            selectedCandidatePositions)
        referenceIndex ...
    ];

    selectedIndices = unique( ...
        selectedIndices, ...
        'stable');

    if numel(selectedIndices) < selectedSamples

        remainingIndices = setdiff( ...
            (1:poolSize).', ...
            selectedIndices, ...
            'stable');

        numberMissing = ...
            selectedSamples - ...
            numel(selectedIndices);

        selectedIndices = [ ...
            selectedIndices
            remainingIndices(1:numberMissing) ...
        ];
    end

    if ~ismember(referenceIndex, selectedIndices)
        error( ...
            'BMLAV41:CurrentPointNotSelected', ...
            'The accepted iterate was not retained in the model.');
    end
end


function [rankValue, rightSingularVectors] = ...
        normalized_geometry_rank( ...
            displacementRows, numberOfVariables)
%NORMALIZED_GEOMETRY_RANK Rank of Delta-normalized displacement rows.
%
% The singular-value extraction must remain scalar-safe for every matrix
% shape. In MATLAB, when S is 1-by-n or n-by-1, DIAG(S) interprets S as a
% vector and constructs a diagonal matrix instead of extracting the
% diagonal. That made rankValue a row vector for a one-direction geometry
% pool and subsequently broke scalar logical operators.

    if isempty(displacementRows)
        rankValue = 0;
        rightSingularVectors = eye(numberOfVariables);
        return;
    end

    [~, singularMatrix, rightSingularVectors] = ...
        svd(displacementRows, 'econ');

    diagonalLength = min(size(singularMatrix));

    if diagonalLength == 0
        singularValues = zeros(0, 1);
    else
        squareLeadingBlock = singularMatrix( ...
            1:diagonalLength, ...
            1:diagonalLength);

        singularValues = diag(squareLeadingBlock);
        singularValues = singularValues(:);
    end

    if isempty(singularValues)
        rankValue = 0;
    else
        tolerance = ...
            max(size(displacementRows))* ...
            eps(max(singularValues));

        rankValue = nnz( ...
            singularValues > tolerance);
    end

    % Enforce the public contract explicitly: geometry rank is one scalar
    % integer in [0, numberOfVariables].
    rankValue = double(rankValue(1));
    rankValue = max( ...
        0, ...
        min(numberOfVariables, rankValue));

    if size(rightSingularVectors, 2) < numberOfVariables
        rightSingularVectors = [ ...
            rightSingularVectors, ...
            null(rightSingularVectors.') ...
        ];
    end
end


function [A, b, info] = ...
        fit_radius_normalized_affine_model( ...
            sampleX, sampleF, xReference, ...
            normalizationRadius, numberOfVariables)
%FIT_RADIUS_NORMALIZED_AFFINE_MODEL SVD regression in z=(x-xk)/Delta.

    numberOfSamples = size(sampleX, 1);

    normalizedX = ...
        (sampleX - xReference.')/ ...
        normalizationRadius;

    designMatrix = [ ...
        ones(numberOfSamples, 1), ...
        normalizedX];

    [U, S, V] = svd(designMatrix, 'econ');
    singularValues = diag(S);

    if isempty(singularValues)
        designTolerance = 0;
        designRank = 0;
        coefficients = zeros( ...
            numberOfVariables + 1, ...
            size(sampleF, 2));
    else
        designTolerance = ...
            max(size(designMatrix))* ...
            eps(max(singularValues));

        designRank = sum( ...
            singularValues > designTolerance);

        if designRank == 0
            coefficients = zeros( ...
                numberOfVariables + 1, ...
                size(sampleF, 2));
        else
            projectedData = ...
                U(:, 1:designRank).'*sampleF;

            scaledData = bsxfun( ...
                @rdivide, ...
                projectedData, ...
                singularValues(1:designRank));

            coefficients = ...
                V(:, 1:designRank)*scaledData;
        end
    end

    info.designMatrixRank = designRank;
    info.designRankTolerance = designTolerance;

    if designRank >= numberOfVariables + 1
        info.designConditionNumber = ...
            singularValues(1)/ ...
            singularValues(numberOfVariables + 1);
    else
        info.designConditionNumber = Inf;
    end

    c = coefficients(1, :).';
    normalizedSlope = ...
        coefficients(2:end, :).';

    A = normalizedSlope/normalizationRadius;
    b = c - A*xReference;

    predictedF = designMatrix*coefficients;

    info.residualNorm = norm( ...
        predictedF - sampleF, ...
        'fro');

    info.normalizationRadius = ...
        normalizationRadius;

    if any(~isfinite(A(:))) || any(~isfinite(b))
        info.matrixRank = 0;
        info.matrixRankTolerance = NaN;
        info.conditionNumber = Inf;
        return;
    end

    singularValuesA = svd(A);

    if isempty(singularValuesA)
        matrixTolerance = 0;
        matrixRank = 0;
    else
        matrixTolerance = ...
            max(size(A))*eps(max(singularValuesA));
        matrixRank = sum( ...
            singularValuesA > matrixTolerance);
    end

    info.matrixRank = matrixRank;
    info.matrixRankTolerance = matrixTolerance;

    if matrixRank >= numberOfVariables
        info.conditionNumber = ...
            singularValuesA(1)/ ...
            singularValuesA(numberOfVariables);
    else
        info.conditionNumber = Inf;
    end
end


function info = ...
        empty_radius_model_info( ...
            numberOfVariables, normalizationRadius)
%EMPTY_RADIUS_MODEL_INFO

    info.designMatrixRank = 0;
    info.designRankTolerance = NaN;
    info.designConditionNumber = Inf;
    info.residualNorm = Inf;
    info.matrixRank = 0;
    info.matrixRankTolerance = NaN;
    info.conditionNumber = Inf;
    info.normalizationRadius = normalizationRadius;
end


function value = ...
        get_option(options, fieldName, defaultValue)
%GET_OPTION

    fieldName = char(fieldName);

    if isfield(options, fieldName)

        value = options.(fieldName);

    else

        value = defaultValue;
    end
end


function validate_options(options)
%VALIDATE_OPTIONS

    requiredFields = { ...
        'tolX', ...
        'tolF', ...
        'maxIterations'};

    for fieldIndex = 1:numel(requiredFields)

        fieldName = requiredFields{fieldIndex};

        if ~isfield(options, fieldName)

            error( ...
                'BMLAV41:MissingOption', ...
                'Falta options.%s.', ...
                fieldName);
        end
    end

    if ~isscalar(options.tolX) || ...
            options.tolX <= 0 || ...
            ~isfinite(options.tolX)

        error( ...
            'BMLAV41:InvalidTolX', ...
            'tolX debe ser un escalar positivo.');
    end

    if ~isscalar(options.tolF) || ...
            options.tolF <= 0 || ...
            ~isfinite(options.tolF)

        error( ...
            'BMLAV41:InvalidTolF', ...
            'tolF debe ser un escalar positivo.');
    end

    if ~isscalar(options.maxIterations) || ...
            options.maxIterations < 1 || ...
            fix(options.maxIterations) ~= ...
            options.maxIterations

        error( ...
            'BMLAV41:' + ...
            "InvalidMaxIterations", ...
            'maxIterations debe ser un entero positivo.');
    end

    if isfield(options, 'maxFunctionEvaluations')

        validInfiniteBudget = ...
            isinf(options.maxFunctionEvaluations) && ...
            options.maxFunctionEvaluations > 0;

        validFiniteBudget = ...
            isfinite(options.maxFunctionEvaluations) && ...
            options.maxFunctionEvaluations >= 1 && ...
            fix(options.maxFunctionEvaluations) == ...
                options.maxFunctionEvaluations;

        if ~isscalar(options.maxFunctionEvaluations) || ...
                ~(validInfiniteBudget || validFiniteBudget)

            error( ...
                'BMLAV41:InvalidMaxFunctionEvaluations', ...
                ['maxFunctionEvaluations must be a positive ' ...
                 'integer or Inf.']);
        end
    end

    if isfield(options, 'initialScale')

        if ~isscalar(options.initialScale) || ...
                ~isfinite(options.initialScale) || ...
                options.initialScale == 1

            error( ...
                'BMLAV41:' + ...
                "InvalidInitialScale", ...
                'initialScale debe ser finito y diferente de 1.');
        end
    end

    if isfield(options, 'memoryLength')

        if ~isscalar(options.memoryLength) || ...
                options.memoryLength < 1 || ...
                fix(options.memoryLength) ~= ...
                options.memoryLength

            error( ...
                'BMLAV41:' + ...
                "InvalidMemoryLength", ...
                'memoryLength debe ser un entero positivo.');
        end
    end

    if isfield(options, 'maxWindowLength')

        if ~isscalar(options.maxWindowLength) || ...
                options.maxWindowLength < 1 || ...
                fix(options.maxWindowLength) ~= ...
                options.maxWindowLength

            error( ...
                'BMLAV41:' + ...
                "InvalidMaxWindowLength", ...
                'maxWindowLength debe ser un entero positivo.');
        end
    end

    if isfield(options, 'maxConditionNumber')

        if ~isscalar(options.maxConditionNumber) || ...
                options.maxConditionNumber <= 1

            error( ...
                'BMLAV41:' + ...
                "InvalidConditionLimit", ...
                'maxConditionNumber debe ser mayor que 1.');
        end
    end

    if isfield(options, 'regularizationRelative')

        if ~isscalar(options.regularizationRelative) || ...
                options.regularizationRelative <= 0 || ...
                ~isfinite(options.regularizationRelative)

            error( ...
                'BMLAV41:' + ...
                "InvalidRegularization", ...
                'regularizationRelative debe ser positivo.');
        end
    end

    if isfield(options, 'maxRelativeStep')

        if ~isscalar(options.maxRelativeStep) || ...
                options.maxRelativeStep <= 0

            error( ...
                'BMLAV41:' + ...
                "InvalidMaximumStep", ...
                'maxRelativeStep debe ser positivo.');
        end
    end

    if isfield(options, 'stagnationPatience')

        if ~isscalar(options.stagnationPatience) || ...
                options.stagnationPatience < 1 || ...
                fix(options.stagnationPatience) ~= ...
                options.stagnationPatience

            error( ...
                'BMLAV41:' + ...
                "InvalidStagnationPatience", ...
                'stagnationPatience debe ser un entero positivo.');
        end
    end

    if isfield( ...
            options, ...
            'minimumRelativeResidualImprovement')

        value = ...
            options.minimumRelativeResidualImprovement;

        if ~isscalar(value) || ...
                value < 0 || ...
                ~isfinite(value)

            error( ...
                'BMLAV41:' + ...
                "InvalidResidualImprovement", ...
                ['minimumRelativeResidualImprovement ' ...
                 'debe ser no negativo.']);
        end
    end
end
