function verification = verify_frozen_core()
%VERIFY_FROZEN_CORE Verify the installed BMLA v4.1-RC numerical core.

    expectedSHA256 = ...
        "363ff1986c1cfee8ca3438fbb779bf574de792b15edfc38a1c1aff6949491d69";

    toolsFolder = fileparts(mfilename('fullpath'));
    repositoryRoot = fileparts(toolsFolder);

    coreFile = fullfile( ...
        repositoryRoot, ...
        'src', ...
        '+bmla', ...
        'private', ...
        'bmla_v4_1_radius_consistent_solver.m');

    if ~isfile(coreFile)
        verification = table( ...
            string(coreFile), ...
            expectedSHA256, ...
            "MISSING", ...
            false, ...
            'VariableNames', { ...
                'File', ...
                'ExpectedSHA256', ...
                'ActualSHA256', ...
                'Match'});
        disp(verification);
        return;
    end

    actualSHA256 = local_sha256(coreFile);

    verification = table( ...
        string(coreFile), ...
        expectedSHA256, ...
        actualSHA256, ...
        actualSHA256 == expectedSHA256, ...
        'VariableNames', { ...
            'File', ...
            'ExpectedSHA256', ...
            'ActualSHA256', ...
            'Match'});

    disp(verification);
end


function digest = local_sha256(filename)

    messageDigest = ...
        java.security.MessageDigest.getInstance('SHA-256');

    inputStream = ...
        java.io.FileInputStream(java.io.File(char(filename)));

    digestStream = ...
        java.security.DigestInputStream( ...
            inputStream, ...
            messageDigest);

    buffer = zeros(1, 1024 * 1024, 'int8');

    while digestStream.read(buffer, 0, numel(buffer)) ~= -1
    end

    digestStream.close();

    hashBytes = typecast(messageDigest.digest(), 'uint8');

    digest = lower(join(compose('%02x', hashBytes), ""));
end
